version: "3.8"
services:
  comfyui:
    image: ghcr.io/freesosaifared/comfyui-docked:cu126-slim
    
    container_name: comfyui_rtx3060
    ports:
      - "8188:8188"
    volumes:
      - ../data:/root
      - ../custom-nodes:/opt/comfyui/custom_nodes
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]