name: Build & Publish Docker image

on:
  push:
    branches: [ rtx3060-config, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./cu126-slim
          push: true
          tags: ghcr.io/FreesoSaiFared/ComfyUI-Docked:cu126-slim,ghcr.io/FreesoSaiFared/ComfyUI-Docked:latest